### ISSUE TITLE
Trying to up load files > 20mb

### ISSUE THREAD

**Issue by wsoutter** [aws-samples/document-translation#7] opened 2023-04-16 18:57 UTC
When uploading a document > 20mb it presents  a warning "no files > 20mb".  If you then try to fix that problem and upload a smaller document, the error message persists. You need to refresh the page to start again.

**Comment by philipws** [comment] 2023-04-17 13:26
Hey @wsoutter thank you for raising this. I am able to reproduce this.

It appears that when the file name/path is the same the browser does not load the file a second time. If the file name is different (E.g. large.pptx, then small.pptx) it works as intended. 

We will look into how to better handle this user experience.

**Comment by philipws** [comment] 2023-04-17 14:09
A fix has been created and merged into upstream. Could you please test and validate.

**Comment by wsoutter** [comment] 2023-04-17 20:43
Thanks @philipws quick turn around - the fix works beautifully!

**Closed** 2023-04-17 20:44 UTC
